version: 2.1

references:
  on_checkout: &on_checkout
    checkout:
      path: nav2_docs
  setup_doc_dependencies: &setup_doc_dependencies
    run:
      name: Install Doc Dependencies
      command: |
        apk --no-cache add python3
        python3 -m ensurepip
        pip3 install sphinx==1.7.5 docutils==0.14 sphinx_rtd_theme breathe==4.9.1 sphinxcontrib-plantuml
        apk --no-cache add make
        apk --no-cache add doxygen
        apk --no-cache add graphviz
        apk --no-cache add ttf-dejavu
        apk --no-cache add openjdk8-jre
        apk --no-cache add bash git openssh
  make_docs: &make_docs
    run:
      command: |
        cd nav2_docs/sphinx_doc
        make html
  store_docs: &store_docs
    store_artifacts:
        path: nav2_docs/sphinx_doc/_build/html
        destination: html
  publish_docs: &publish_docs
    run:
      command: |
        cd nav2_docs/sphinx_doc
        make publish
  install_deployment_key: &install_deployment_key
    add_ssh_keys:
      fingerprints:
        - "0e:8e:90:bf:3d:a9:04:d9:04:b4:62:38:a5:3b:90:7d"

commands:
  install_doc_dependencies:
    description: "Install documentation dependencies"
    steps:
      - *setup_doc_dependencies
  build_docs:
    description: "Build docs"
    steps:
      - *make_docs
      - *store_docs
  publish_docs_to_gh_pages_branch:
    description: "Commit newly built docs to gh-pages branch"
    steps:
      - *publish_docs

executors:
  docs_exec:
    docker:
      - image: alpine:latest
    working_directory: /

jobs:
  docs_build:
    executor: docs_exec
    steps:
      - install_doc_dependencies
      - *on_checkout
      - build_docs
      - persist_to_workspace:
          root: nav2_docs
          paths:
            - sphinx_doc
  docs_publish:
    executor: docs_exec
    steps:
      - install_doc_dependencies
      - *on_checkout
      - *install_deployment_key
      - attach_workspace:
          at: nav2_docs
      - publish_docs_to_gh_pages_branch

workflows:
  version: 2
  build_and_publish_docs:
    jobs:
      - docs_build
      - docs_publish:
          requires:
            - docs_build
          filters:
            branches:
              only: master
